/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MechanicRouteImport } from './routes/mechanic'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as QuarantineRouteImport } from './routes/quarantine'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SentinelRouteImport } from './routes/sentinel'
import { Route as StackRouteImport } from './routes/stack'
import { Route as TableRouteImport } from './routes/table'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicRoute = MechanicRouteImport.update({
  id: '/mechanic',
  path: '/mechanic',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarantineRoute = QuarantineRouteImport.update({
  id: '/quarantine',
  path: '/quarantine',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SentinelRoute = SentinelRouteImport.update({
  id: '/sentinel',
  path: '/sentinel',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoomsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/forge': typeof ForgeRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/mechanic': typeof MechanicRoute
  '/oracle': typeof OracleRoute
  '/quarantine': typeof QuarantineRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/sentinel': typeof SentinelRoute
  '/stack': typeof StackRoute
  '/table': typeof TableRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/forge': typeof ForgeRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/mechanic': typeof MechanicRoute
  '/oracle': typeof OracleRoute
  '/quarantine': typeof QuarantineRoute
  '/sentinel': typeof SentinelRoute
  '/stack': typeof StackRoute
  '/table': typeof TableRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/forge': typeof ForgeRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/mechanic': typeof MechanicRoute
  '/oracle': typeof OracleRoute
  '/quarantine': typeof QuarantineRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/sentinel': typeof SentinelRoute
  '/stack': typeof StackRoute
  '/table': typeof TableRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drive'
    | '/forge'
    | '/gallery'
    | '/login'
    | '/mechanic'
    | '/oracle'
    | '/quarantine'
    | '/rooms'
    | '/sentinel'
    | '/stack'
    | '/table'
    | '/rooms/$slug'
    | '/rooms/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drive'
    | '/forge'
    | '/gallery'
    | '/login'
    | '/mechanic'
    | '/oracle'
    | '/quarantine'
    | '/sentinel'
    | '/stack'
    | '/table'
    | '/rooms/$slug'
    | '/rooms'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/drive'
    | '/forge'
    | '/gallery'
    | '/login'
    | '/mechanic'
    | '/oracle'
    | '/quarantine'
    | '/rooms'
    | '/sentinel'
    | '/stack'
    | '/table'
    | '/rooms/$slug'
    | '/rooms/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveRoute: typeof DriveRoute
  ForgeRoute: typeof ForgeRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MechanicRoute: typeof MechanicRoute
  OracleRoute: typeof OracleRoute
  QuarantineRoute: typeof QuarantineRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SentinelRoute: typeof SentinelRoute
  StackRoute: typeof StackRoute
  TableRoute: typeof TableRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanic': {
      id: '/mechanic'
      path: '/mechanic'
      fullPath: '/mechanic'
      preLoaderRoute: typeof MechanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarantine': {
      id: '/quarantine'
      path: '/quarantine'
      fullPath: '/quarantine'
      preLoaderRoute: typeof QuarantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentinel': {
      id: '/sentinel'
      path: '/sentinel'
      fullPath: '/sentinel'
      preLoaderRoute: typeof SentinelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RoomsRouteChildren {
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveRoute: DriveRoute,
  ForgeRoute: ForgeRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MechanicRoute: MechanicRoute,
  OracleRoute: OracleRoute,
  QuarantineRoute: QuarantineRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SentinelRoute: SentinelRoute,
  StackRoute: StackRoute,
  TableRoute: TableRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
